from __future__ import annotations

from .domain import EvidenceRecord


EVIDENCE_REGISTRY: dict[str, EvidenceRecord] = {
    "method.full.transformers": EvidenceRecord(
        "method.full.transformers",
        "Full fine-tuning updates all model parameters.",
        "https://huggingface.co/docs/transformers/training",
        "official-documentation",
        "Transformers causal language-model training",
        "documented",
    ),
    "method.lora.paper": EvidenceRecord(
        "method.lora.paper",
        "LoRA injects trainable low-rank matrices while freezing base weights.",
        "https://arxiv.org/abs/2106.09685",
        "research-paper",
        "Method definition; not an Aptus quality guarantee",
        "paper-reported",
        "arXiv:2106.09685",
    ),
    "method.qlora.paper": EvidenceRecord(
        "method.qlora.paper",
        "QLoRA uses a frozen four-bit base with trainable LoRA adapters.",
        "https://arxiv.org/abs/2305.14314",
        "research-paper",
        "NF4 and double-quantized QLoRA method; hardware support still required",
        "paper-reported",
        "arXiv:2305.14314",
    ),
    "method.dora.paper": EvidenceRecord(
        "method.dora.paper",
        "DoRA decomposes pretrained weights into magnitude and direction and applies a low-rank update to the directional component.",
        "https://arxiv.org/abs/2402.09353",
        "research-paper",
        "Method definition; not evidence that an Aptus runtime path is implemented or calibrated",
        "paper-reported",
        "arXiv:2402.09353",
    ),
    "method.bitfit.paper": EvidenceRecord(
        "method.bitfit.paper",
        "BitFit freezes a pretrained transformer and updates only its existing bias terms.",
        "https://arxiv.org/abs/2106.10199",
        "research-paper",
        "Method definition and masked-language-model experiments; applicability depends on the exact architecture exposing biases",
        "paper-reported",
        "arXiv:2106.10199",
    ),
    "method.loreft.paper": EvidenceRecord(
        "method.loreft.paper",
        "LoReFT learns low-rank interventions on hidden representations rather than weight adapters.",
        "https://arxiv.org/abs/2404.03592",
        "research-paper",
        "Method definition; requires an intervention-aware runtime, collator, checkpoint, and export contract",
        "paper-reported",
        "arXiv:2404.03592",
    ),
    "method.aflora.paper": EvidenceRecord(
        "method.aflora.paper",
        "AFLoRA dynamically evaluates and freezes low-rank parameter groups during training.",
        "https://arxiv.org/abs/2403.13269",
        "research-paper",
        "Method definition; dynamic optimizer and checkpoint state are not implemented by Aptus",
        "paper-reported",
        "arXiv:2403.13269",
    ),
    "method.bilora.paper": EvidenceRecord(
        "method.bilora.paper",
        "BiLoRA uses bilevel optimization over disjoint data partitions with a pseudo-SVD low-rank parameterization.",
        "https://arxiv.org/abs/2403.13037",
        "research-paper",
        "Method definition; requires a dedicated bilevel trainer and partition contract",
        "paper-reported",
        "arXiv:2403.13037",
    ),
    "method.adalora.paper": EvidenceRecord(
        "method.adalora.paper",
        "AdaLoRA allocates a changing rank budget across pseudo-SVD parameter groups using importance scores and a pruning schedule.",
        "https://arxiv.org/abs/2303.10512",
        "research-paper",
        "Method definition and reported experiments; Aptus still requires a pinned adaptive-budget compiler and restart contract",
        "paper-reported",
        "arXiv:2303.10512",
    ),
    "method.sharelora.paper": EvidenceRecord(
        "method.sharelora.paper",
        "ShareLoRA shares one or both low-rank factors across compatible layers.",
        "https://arxiv.org/abs/2406.10785",
        "research-paper",
        "Method definition; serialization and distributed synchronization require independent verification",
        "paper-reported",
        "arXiv:2406.10785",
    ),
    "method.bitsandbytes.int8": EvidenceRecord(
        "method.bitsandbytes.int8",
        "Bitsandbytes provides eight-bit model loading for supported CUDA environments.",
        "https://huggingface.co/docs/transformers/quantization/bitsandbytes",
        "official-documentation",
        "Transformers bitsandbytes integration",
        "documented",
    ),
    "estimate.memory.v2": EvidenceRecord(
        "estimate.memory.v2",
        "Aptus v2 reports an analytic point estimate and an explicit heuristic upper envelope.",
        "aptus://methodology/memory-envelope-v2",
        "aptus-methodology",
        "Uncalibrated component accounting; exact real-model pilot required",
        "uncalibrated",
    ),
    "policy.qwen3-moe.mlx-qlora.v1": EvidenceRecord(
        "policy.qwen3-moe.mlx-qlora.v1",
        "Aptus defines one exact Qwen3 MoE MLX-LM QLoRA path as eligible for gated validation.",
        "aptus://operations/evidence/2026-07-28-qwen3-moe-admission",
        "aptus-compatibility-policy",
        "Exact qwen3_moe and Qwen3MoeForCausalLM identity, reviewed mixed-bit layout, routed topology, and attention-only adapter scope",
        "implementation-reviewed",
        "1.0.0",
    ),
    "admission.qwen3-30b-a3b.memory-blocked.2026-07-28": EvidenceRecord(
        "admission.qwen3-30b-a3b.memory-blocked.2026-07-28",
        "The exact 30B target-host attempt passed dependency validation and then stopped before model loading at live unified-memory admission.",
        "aptus://operations/evidence/2026-07-28-qwen3-moe-admission",
        "measured-admission-record",
        "Exact pinned Qwen3 30B-A3B revision on the recorded Apple Silicon host; not a passing model-data or pilot result",
        "measured-blocked",
        "e9675aa3ca5f900ccef55267914466d55ab325fa",
    ),
    "policy.qwen2-24l.mlx-qlora.v1": EvidenceRecord(
        "policy.qwen2-24l.mlx-qlora.v1",
        "Aptus defines one reviewed 24-layer dense Qwen2 MLX-LM QLoRA runtime configuration footprint as eligible for gated validation.",
        "aptus://operations/evidence/2026-07-27-mlx-lm-acceptance",
        "aptus-compatibility-policy",
        "Reviewed qwen, qwen2, and Qwen2ForCausalLM identity; 24-layer dense topology; uniform four-bit group-size-64 layout; and dense adapter targets. Runtime evidence remains artifact-scoped.",
        "implementation-reviewed",
        "1.0.0",
    ),
    "policy.gemma4.mlx.v1": EvidenceRecord(
        "policy.gemma4.mlx.v1",
        "Aptus defines one Gemma 4 dense MLX-LM family path as eligible for gated validation.",
        "aptus://product/lane-6-gemma4-family-admission",
        "aptus-compatibility-policy",
        "Exact gemma4 / gemma4_text / Gemma4ForConditionalGeneration identity; inspect-declared layers and bits 1-16; dense topology. Runtime evidence remains artifact-scoped and pilot-required.",
        "implementation-reviewed",
        "1.0.0",
    ),
    "policy.gemma4-unified.mlx.v1": EvidenceRecord(
        "policy.gemma4-unified.mlx.v1",
        "Aptus recognizes Gemma 4 unified as a second exact identity under family gemma4. Bound MLX-LM does not load that architecture.",
        "aptus://product/lane-7-gemma4-unified",
        "aptus-compatibility-policy",
        "Exact gemma4 / gemma4_unified_text / Gemma4UnifiedForConditionalGeneration identity; dense topology; unsupported by the current compiler contract until mlx-lm loads this architecture. Not a no-policy-match. Not quality.",
        "implementation-reviewed",
        "1.0.0",
    ),
    "policy.gemma4-moe.mlx.v1": EvidenceRecord(
        "policy.gemma4-moe.mlx.v1",
        "Aptus defines one Gemma 4 MoE MLX-LM QLoRA path as eligible for gated validation.",
        "aptus://product/lane-9-gemma4-moe",
        "aptus-compatibility-policy",
        "Exact gemma4_moe / gemma4_text / Gemma4ForConditionalGeneration identity; 4-bit group-64 default plus 8-bit router.proj overrides; routed topology with no shared expert; attention-only q/k/v/o adapters. Resident weight is not active parameters. Runtime evidence remains artifact-scoped and pilot-required. Not quality. Not CUDA MoE.",
        "implementation-reviewed",
        "1.0.0",
    ),
    "runtime.qwen2-0.5b.mlx-qlora.2026-07-27": EvidenceRecord(
        "runtime.qwen2-0.5b.mlx-qlora.2026-07-27",
        "Two clean historical workflows for the exact pinned Qwen2.5 0.5B artifact reached measured-run-pass under Aptus training-plan v2 and bundle v2.",
        "aptus://operations/evidence/2026-07-27-mlx-lm-acceptance",
        "measured-runtime-record",
        "Exact mlx-community/Qwen2.5-0.5B-Instruct-4bit revision 53a32aee5e9447773fd2b85988395066aef3700a on the recorded Apple M5 Pro host, runtime, and dataset. This historical result does not validate current contracts or other matching artifacts.",
        "measured-historical",
        "53a32aee5e9447773fd2b85988395066aef3700a",
    ),
}


def evidence_for(*evidence_ids: str) -> tuple[EvidenceRecord, ...]:
    missing = [item for item in evidence_ids if item not in EVIDENCE_REGISTRY]
    if missing:
        raise KeyError(f"Unknown evidence ID(s): {', '.join(missing)}")
    return tuple(EVIDENCE_REGISTRY[item] for item in evidence_ids)
