from __future__ import annotations

import json
from pathlib import Path

from . import plan_contract
from .catalog import bundle_requirements
from .domain import TrainingPlan, ValidationReport, to_primitive


TRAIN_SCRIPT = r'''#!/usr/bin/env python3
"""Training entrypoint generated by Aptus from plan.json."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

from plan_contract import bundle_fingerprint, validate_plan_payload


ROOT = Path(__file__).resolve().parent
PLAN_PATH = ROOT / "plan.json"
VALIDATION_REPORT_PATH = ROOT / "validation-report.json"


def load_plan() -> dict:
    return json.loads(PLAN_PATH.read_text(encoding="utf-8"))


def update_validation_state(state: str, evidence: str) -> None:
    report = json.loads(VALIDATION_REPORT_PATH.read_text(encoding="utf-8"))
    current_fingerprint = bundle_fingerprint(ROOT)
    if report.get("artifact_fingerprint") != current_fingerprint:
        raise ValueError(
            "Validation report does not match the current bundle artifacts."
        )
    state_rank = {
        "invalid": 0,
        "static-pass": 1,
        "environment-pass": 2,
        "smoke-pass": 3,
    }
    current_state = report.get("state", "invalid")
    if current_state == "invalid" or any(
        finding.get("severity") == "error"
        for finding in report.get("findings", [])
        if isinstance(finding, dict)
    ):
        raise ValueError("Cannot promote an invalid static validation report.")
    if state not in state_rank:
        raise ValueError(f"Unknown validation state: {state}")
    if state_rank[state] > state_rank.get(current_state, 0):
        report["state"] = state
    runtime_evidence = report.setdefault("runtime_evidence", [])
    if evidence not in runtime_evidence:
        runtime_evidence.append(evidence)
    VALIDATION_REPORT_PATH.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def load_texts(path: Path) -> list[str]:
    suffix = path.suffix.lower()
    if suffix == ".jsonl":
        rows = [
            json.loads(line)
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
    elif suffix == ".json":
        value = json.loads(path.read_text(encoding="utf-8"))
        rows = value if isinstance(value, list) else value.get("train", [value])
    elif suffix == ".csv":
        with path.open("r", encoding="utf-8", newline="") as source:
            rows = list(csv.DictReader(source))
    elif suffix == ".txt":
        return [
            line.strip()
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
    else:
        raise ValueError(f"Unsupported dataset format: {suffix}")
    texts = [row.get("text") for row in rows if isinstance(row, dict)]
    if not texts or not all(isinstance(text, str) and text.strip() for text in texts):
        raise ValueError("Every generated-training example must contain non-empty text.")
    return texts


def run_smoke(plan: dict) -> None:
    import torch
    from peft import LoraConfig, get_peft_model
    from transformers import LlamaConfig, LlamaForCausalLM

    torch.manual_seed(7)
    config = LlamaConfig(
        vocab_size=128,
        hidden_size=32,
        intermediate_size=64,
        num_hidden_layers=1,
        num_attention_heads=4,
        num_key_value_heads=4,
        max_position_embeddings=64,
    )
    model = LlamaForCausalLM(config)
    adapter = LoraConfig(
        r=min(plan["recommended"]["rank"], 8),
        lora_alpha=min(plan["recommended"]["alpha"], 16),
        lora_dropout=0.0,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, adapter)
    optimizer = torch.optim.AdamW(
        [parameter for parameter in model.parameters() if parameter.requires_grad],
        lr=1e-3,
    )
    input_ids = torch.randint(0, config.vocab_size, (2, 16))
    loss = model(input_ids=input_ids, labels=input_ids).loss
    if not torch.isfinite(loss):
        raise RuntimeError("Offline smoke loss is not finite.")
    loss.backward()
    optimizer.step()
    optimizer.zero_grad(set_to_none=True)
    update_validation_state(
        "smoke-pass",
        "Offline tiny-model Transformers/PEFT optimizer step passed.",
    )
    print(f"Aptus offline smoke passed; loss={loss.item():.6f}")


def run_training(plan: dict) -> None:
    import torch
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
    from torch.utils.data import DataLoader, Dataset
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

    candidate = plan["recommended"]
    model_spec = plan["model"]
    dataset_path = Path(plan["dataset"]["source_path"])
    texts = load_texts(dataset_path)
    tokenizer = AutoTokenizer.from_pretrained(
        model_spec["model_id"],
        revision=model_spec["revision"],
        trust_remote_code=False,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    quantization_config = None
    if candidate["method"] == "qlora":
        quantization_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=torch.bfloat16
            if candidate["precision"] == "bf16"
            else torch.float16,
        )

    dtype = torch.bfloat16 if candidate["precision"] == "bf16" else torch.float16
    model = AutoModelForCausalLM.from_pretrained(
        model_spec["model_id"],
        revision=model_spec["revision"],
        trust_remote_code=False,
        torch_dtype=dtype,
        quantization_config=quantization_config,
        device_map={"": 0},
    )
    if candidate["method"] == "qlora":
        model = prepare_model_for_kbit_training(
            model,
            use_gradient_checkpointing=True,
        )
    else:
        model.gradient_checkpointing_enable()

    adapter = LoraConfig(
        r=candidate["rank"],
        lora_alpha=candidate["alpha"],
        lora_dropout=0.05,
        target_modules=candidate["target_modules"],
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, adapter)

    class TextDataset(Dataset):
        def __len__(self) -> int:
            return len(texts)

        def __getitem__(self, index: int) -> dict[str, torch.Tensor]:
            encoded = tokenizer(
                texts[index],
                truncation=True,
                max_length=plan["target"]["sequence_length"],
                padding="max_length",
                return_tensors="pt",
            )
            input_ids = encoded["input_ids"].squeeze(0)
            attention_mask = encoded["attention_mask"].squeeze(0)
            labels = input_ids.clone()
            labels[attention_mask == 0] = -100
            return {
                "input_ids": input_ids,
                "attention_mask": attention_mask,
                "labels": labels,
            }

    loader = DataLoader(
        TextDataset(),
        batch_size=candidate["micro_batch_size"],
        shuffle=True,
    )
    optimizer = torch.optim.AdamW(
        [parameter for parameter in model.parameters() if parameter.requires_grad],
        lr=candidate["learning_rate"],
    )
    accumulation = candidate["gradient_accumulation_steps"]
    model.train()
    optimizer.zero_grad(set_to_none=True)
    for _epoch in range(plan["target"]["max_epochs"]):
        window_tokens = 0
        for step, batch in enumerate(loader, start=1):
            batch = {key: value.to(model.device) for key, value in batch.items()}
            active_tokens = (batch["labels"] != -100).sum()
            loss = model(**batch).loss * active_tokens
            loss.backward()
            window_tokens += int(active_tokens.item())
            if step % accumulation == 0 or step == len(loader):
                if window_tokens <= 0:
                    raise RuntimeError("Accumulation window has no training tokens.")
                for parameter in model.parameters():
                    if parameter.grad is not None:
                        parameter.grad.div_(window_tokens)
                optimizer.step()
                optimizer.zero_grad(set_to_none=True)
                window_tokens = 0
    output_dir = ROOT / "output-model"
    model.save_pretrained(output_dir, safe_serialization=True)
    tokenizer.save_pretrained(output_dir)
    print(f"Training complete: {output_dir}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run an Aptus training bundle.")
    parser.add_argument("--validate-only", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    arguments = parser.parse_args()

    plan = load_plan()
    errors = validate_plan_payload(plan, verify_dataset=True)
    if errors:
        raise ValueError("Invalid Aptus plan: " + " | ".join(errors))
    if arguments.validate_only:
        update_validation_state(
            "environment-pass",
            "Dependency-free generated plan validation passed.",
        )
        print("Aptus bundle validation passed.")
        return 0
    if arguments.smoke:
        run_smoke(plan)
        return 0
    run_training(plan)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


VALIDATE_SCRIPT = r'''#!/usr/bin/env python3
"""Run the dependency-free Aptus bundle validation entrypoint."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


root = Path(__file__).resolve().parent
completed = subprocess.run(
    [sys.executable, str(root / "train.py"), "--validate-only"],
    cwd=root,
    check=False,
)
raise SystemExit(completed.returncode)
'''


def _plan_payload(plan: TrainingPlan) -> dict:
    payload = to_primitive(plan)
    payload["recommended"]["memory"]["estimated_peak_bytes"] = (
        plan.recommended.memory.estimated_peak_bytes
    )
    for candidate_payload, candidate in zip(
        payload["candidates"],
        plan.candidates,
        strict=True,
    ):
        candidate_payload["memory"]["estimated_peak_bytes"] = (
            candidate.memory.estimated_peak_bytes
        )
    return payload


def _requirements(plan: TrainingPlan) -> str:
    return "\n".join(bundle_requirements(plan.recommended.method.value)) + "\n"


def _readme(plan: TrainingPlan) -> str:
    return f"""# Aptus generated training bundle

Method: `{plan.recommended.method.value}`

This bundle was compiled from `plan.json`. Review that file's assumptions,
warnings, rejection reasons, and low-until-calibrated memory confidence before
spending GPU time.

```bash
python validate.py
python train.py --smoke
python train.py
```

`--smoke` is offline and uses a tiny synthetic Llama configuration. It validates
the Transformers/PEFT adapter contract, not the selected model's quantized memory
fit. Normal training can download the explicitly named model revision and
requires the local dataset recorded in `plan.json`.
"""


def generate_bundle(plan: TrainingPlan, output_dir: Path) -> ValidationReport:
    output_dir = output_dir.resolve()
    if output_dir.exists() and any(output_dir.iterdir()):
        raise FileExistsError(f"Bundle output is not empty: {output_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)

    (output_dir / "plan.json").write_text(
        json.dumps(_plan_payload(plan), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (output_dir / "plan_contract.py").write_text(
        Path(plan_contract.__file__).read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    (output_dir / "train.py").write_text(TRAIN_SCRIPT, encoding="utf-8")
    (output_dir / "validate.py").write_text(VALIDATE_SCRIPT, encoding="utf-8")
    (output_dir / "requirements.txt").write_text(
        _requirements(plan),
        encoding="utf-8",
    )
    (output_dir / "README.md").write_text(_readme(plan), encoding="utf-8")

    from .validation import validate_bundle

    return validate_bundle(output_dir)
